export const products = [
  {
    title: `Mixed Flower Honey`,
    path: `/product/mixed-flower-honey`,
    product: `Mixed Flower`,
    nextProduct: `/product/royal-jelly`,
    previousProduct: `/product/royal-jelly`,
    wholesalePrice: `Wholesale: RM 580 / 10kg`,
    resellerPrice: `Reseller: RM 58 / 0.7kg`,
    description: `Most famous honey on our list. The mixture of the flower depends on bees. Each batch has difference smell and taste: bees are harvest flowers by its instinct). The honey colour is slightly different for each batch.`,
  },
  {
    title: `Durian Flower Honey`,
    path: `/product/durian-flower-honey`,
    product: `Durian Flower`,
    nextProduct: `/product/royal-jelly`,
    previousProduct: `/product/mixed-flower-honey`,
    wholesalePrice: `Wholesale: RM 580 / 10 kg / Bottle`,
    resellerPrice: `Reseller: RM 58 / 0.7 kg /  Bottle`,
    description: `Don't expect it tastes like "Durian", the bee is harvesting the flower, not the fruit. It tastes sweet and smells 30% like wild honey & 70% flower honey (taste & smell is opinionated). The moisture level is high due to the forest environment. If the stock is running out, then we need to wait for the next "Durian" season. During this time, the bee farmer will move the hive to harvest another flower. Honey is filtered and packed in food grade bottles.`,
  },
  {
    title: `Royal Jelly`,
    path: `/product/royal-jelly`,
    product: `Royal Jelly`,
    nextProduct: `/product/mixed-flower-honey`,
    previousProduct: `/product/mixed-flower-honey`,
    wholesalePrice: `Wholesale: RM 450 / 500g `,
    resellerPrice: `Reseller: RM 240 / 200g`,
    description: `Most natural healthcare gift from the mother earth & the bees. Do you know working bee live around 90days? What about the queen which eats royal jelly as food? She can live for 1460 days.`,
  },
]
